sudo: require
language: cpp
compiler:
  - g++
  - clang++

before_install:
  # g++
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  # clang++
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq
#  - sudo pip install codecov

install:
  # g++
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-5; fi 
  - if [ "$CXX" == "g++" ]; then sudo pip install codecov; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90; fi

  # clang++
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
#  - if [ "$CXX" == "clang++" ]; then sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++3.4 90; fi

before_script:
  - autoreconf -fi

script: 
  - $CXX --version
  - if [ "$CXX" == "g++" ]; then export CXXFLAGS="-coverage"; fi
  - ./configure
  - make
  - make check
  - if [ "$CXX" == "g++" ]; then ./get_code_cov.sh; fi

after_success:
  - if [ "$CXX" == "g++" ]; then codecov; fi
